spring:
  application.name: budjet-management
  main.banner-mode: off
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  mvc.static-path-pattern: /**
  web.resources.static-locations: file:./budget-management-fe/dist/
