spring:
  application.name: budjet-management
  main.banner-mode: off
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  mvc.static-path-pattern: /**
  web.resources.static-locations: file:./budget-management-fe/dist/
  datasource:
    url: ${RUKULA_APP_POSTGRES_URL:jdbc:postgres://127.0.0.1:5432/budgets-service}
    username: ${RUKULA_APP_POSTGRES_USERNAME:budgets-service}
    password: ${RUKULA_APP_POSTGRES_PASSWORD:password}
  docker:
    compose:
      lifecycle-management: start_only

spring.security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8666/realms/test-realm
          jwk-set-uri: http://localhost:8666/realms/test-realm/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: test-client
            client-secret: test-client-secret
            scope: openid
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuerUri: http://localhost:8666/realms/test-realm
