spring:
  application.name: budjet-management
  main.banner-mode: off
  jpa:
    open-in-view: false
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  mvc.static-path-pattern: /**
  web.resources.static-locations: file:./budget-management-fe/dist/

spring.datasource:
  url: ${RUKULA_APP_POSTGRES_URL:no_default}
  username: ${RUKULA_APP_POSTGRES_USERNAME:no_default}
  password: ${RUKULA_APP_POSTGRES_PASSWORD:no_default}